### PR TITLE
A-10C DSMS UI Tweaks

### PR DESCRIPTION
**Pull request by ilominar**
Aligned widgets. Visibility now context sensitive so only relevant widgets for weapon settings are visible.

Part 2 of the DSMS UI tweaks.

Layout was changed for alignment, also there was some additional functional separation to group parameters that were per-DSMS versus parameters that are per-munition.

Munition parameters are now context sensitive. Only those widgets relevant to parameters associated with the munition are visible (so, for example, auto lase controls are hidden for non-laser-guided weapons).

### CODE REVIEW

**Review by fizzle77 — APPROVED** [review]
Overall very nice and a clear improvement. One suggestion is to make more liberal use of auto widths. I see text cut off in lots of places in the app on Windows 10, including this screen now, e.g the Maverick D/G/H/K line and "Escape Maneuver":

cutoff-text-png

**Review by fizzle77 — CHANGES_REQUESTED** [review]
Just noticed you left out the autolase time textbox, presumably by accident. This defaults to 0 so not having it is a breaking change we should fix before merging.

**Review by fizzle77 — APPROVED** [review]
Oops it appears once you check autolase, which makes sense. Just like the ripple distance. Never mind, carry on.

**Comment by ilominar** [comment]
I'll fix the auto width. I was trying to get around an annoying visual tick where WinUI renders the ListView (probably sized to the width of the visible rows?) then snaps it to a wider size (probably sized to the width of all content?).

**Comment by fizzle77** [comment]
I know exactly the visual tick you describe and suspected that's what you were doing.

**Pull request merged**
